name: custom_mouse_cursor
description: Custom mouse cursors for Flutter which are devicePixelRatio aware.
version: 1.0.0
homepage: https://github.com/timmaffett/custom_mouse_cursor

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  crypto: ^3.0.2
  flutter:
    sdk: flutter
  # google_fonts: ^4.0.3
  #win32: #^3.1.3
  #  path: ../win32/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      #windows:
      #  pluginClass: CustomMouseCursorPlugin
      macos:
        pluginClass: CustomMouseCursorPlugin
      linux:
        pluginClass: CustomMouseCursorPlugin

  # assets:
  #   - assets/
  #   - assets/cursors/
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
