name: custom_mouse_cursor
description: Custom mouse cursors for Flutter which are devicePixelRatio aware.
version: 1.1.3
homepage: https://github.com/timmaffett/custom_mouse_cursor
screenshots:
  - description: 'Example program illustrating use of CustomMouseCursor cursors.'
    path: media/example_app_windowcapture_01.png

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  chalkdart: ^3.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: CustomMouseCursorPlugin
      linux:
        pluginClass: CustomMouseCursorPlugin
